"""The vitruvio kernel: configuration, brain discovery, identity, paths and errors.

This package answers three questions and nothing else: *which brain*, *who am I*, and *under what policy*.
It depends on pydantic and the Boltzmann SDK's value types, and on nothing heavier -- no index engine, no
embedder, no registry client. That is deliberate and load-bearing: ``vitruvio config show`` and
``vitruvio brain use`` must start in tens of milliseconds, and if configuration lived alongside the runtime
then importing it would drag in ``usearch`` and the index registry.

Every other vitruvio package imports this one; this one imports no other vitruvio package.
"""

from __future__ import annotations

from vitruvio.kernel import updates
from vitruvio.kernel.config import (
    DEFAULT_TEXT_EMBEDDER,
    ActorSpec,
    BrainSpec,
    EmbedderSpec,
    IndexSpec,
    IngestSpec,
    NamedBrainSpec,
    Origin,
    PlannerConfig,
    PolicyProfile,
    PolicySpec,
    ProjectConfig,
    ProjectSpec,
    ReconcileStrategy,
    RegistrySpec,
    ResolvedConfig,
    SourceSpec,
    default_indices,
)
from vitruvio.kernel.discovery import (
    ENV_ACTOR_ID,
    ENV_ACTOR_KIND,
    ENV_BRAIN,
    ENV_CONFIG,
    ENV_PROJECT,
    find_config_file,
    forget_project,
    known_projects,
    load_project,
    note_brain,
    parse_actor_kind,
    project_config_file,
    read_state,
    register_project,
    remember_brain,
    resolve,
    select_config_file,
    selected_brain,
    selection_key,
    update_config,
    walk_up,
    write_state,
)
from vitruvio.kernel.errors import (
    ActorUnknownError,
    BrainNotFoundError,
    BrainNotSelectedError,
    CandidatesRejectedError,
    ConfigError,
    CredentialError,
    ExitCode,
    ProjectNotKnownError,
    PublishForbiddenError,
    ReconciliationOpenError,
    SourceError,
    SourceUnavailableError,
    UsageError,
    VitruvioError,
)
from vitruvio.kernel.paths import (
    CONFIG_FILE,
    DERIVED_DIR,
    cache_home,
    config_home,
    credentials_file,
    derived_dir,
    is_layout,
    model_cache,
    plugin_dir,
    prepare_model_cache,
    state_file,
    state_home,
)
from vitruvio.kernel.secrets import (
    REDACTED,
    TOKEN_URL,
    Secret,
    from_environment,
    provider_key,
    registry_credentials,
)
from vitruvio.kernel.version import __version__

__all__ = [
    "CONFIG_FILE",
    "DEFAULT_TEXT_EMBEDDER",
    "DERIVED_DIR",
    "ENV_ACTOR_ID",
    "ENV_ACTOR_KIND",
    "ENV_BRAIN",
    "ENV_CONFIG",
    "ENV_PROJECT",
    "REDACTED",
    "TOKEN_URL",
    "ActorSpec",
    "ActorUnknownError",
    "CandidatesRejectedError",
    "BrainNotFoundError",
    "BrainNotSelectedError",
    "BrainSpec",
    "ConfigError",
    "CredentialError",
    "EmbedderSpec",
    "ExitCode",
    "IndexSpec",
    "IngestSpec",
    "Origin",
    "PlannerConfig",
    "PublishForbiddenError",
    "ReconciliationOpenError",
    "PolicyProfile",
    "ReconcileStrategy",
    "PolicySpec",
    "NamedBrainSpec",
    "ProjectConfig",
    "ProjectNotKnownError",
    "ProjectSpec",
    "RegistrySpec",
    "ResolvedConfig",
    "Secret",
    "SourceError",
    "SourceSpec",
    "SourceUnavailableError",
    "UsageError",
    "VitruvioError",
    "__version__",
    "updates",
    "cache_home",
    "config_home",
    "credentials_file",
    "default_indices",
    "derived_dir",
    "find_config_file",
    "forget_project",
    "from_environment",
    "is_layout",
    "known_projects",
    "load_project",
    "model_cache",
    "note_brain",
    "parse_actor_kind",
    "plugin_dir",
    "prepare_model_cache",
    "project_config_file",
    "provider_key",
    "read_state",
    "register_project",
    "registry_credentials",
    "remember_brain",
    "resolve",
    "select_config_file",
    "selected_brain",
    "selection_key",
    "state_file",
    "state_home",
    "update_config",
    "walk_up",
    "write_state",
]
