"""Generate the statically visible ``BrainService`` facade from the operation catalogue."""

from __future__ import annotations

import argparse
import ast
import copy
import importlib.util
import subprocess
import sys
from pathlib import Path

from vitruvio.runtime.operation_catalogue import OPERATION_CATALOGUE, Exposure, OperationDomain

TARGET = Path(__file__).with_name("_generated_facade.py")


def _source_path(domain: OperationDomain) -> Path:
    """Resolve an operations module without importing ``vitruvio.runtime`` and its facade."""
    found = importlib.util.find_spec(domain.module)
    if found is None or found.origin is None:
        raise RuntimeError(f"could not resolve {domain.module}")
    return Path(found.origin)


def _method(domain: OperationDomain, name: str) -> ast.FunctionDef | ast.AsyncFunctionDef:
    tree = ast.parse(_source_path(domain).read_text(encoding="utf-8"))
    owner = next(
        (node for node in tree.body if isinstance(node, ast.ClassDef) and node.name == domain.class_name),
        None,
    )
    if owner is None:
        raise RuntimeError(f"{domain.qualified_name} does not exist")
    method = next(
        (
            node
            for node in owner.body
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == name
        ),
        None,
    )
    if method is None:
        raise RuntimeError(f"{domain.qualified_name}.{name} does not exist")
    return method


def _summary(method: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    doc = ast.get_docstring(method, clean=True) or method.name.replace("_", " ").capitalize()
    return doc.split("\n\n", 1)[0].replace("\n", " ")


def _forwarder(domain: OperationDomain, name: str) -> ast.FunctionDef | ast.AsyncFunctionDef:
    source = _method(domain, name)
    args = copy.deepcopy(source.args)
    positional: list[ast.expr] = [
        ast.Name(id=argument.arg, ctx=ast.Load())
        for argument in (*args.posonlyargs, *args.args)
        if argument.arg != "self"
    ]
    if args.vararg is not None:
        positional.append(ast.Starred(value=ast.Name(id=args.vararg.arg, ctx=ast.Load()), ctx=ast.Load()))
    keywords = [
        ast.keyword(arg=argument.arg, value=ast.Name(id=argument.arg, ctx=ast.Load())) for argument in args.kwonlyargs
    ]
    if args.kwarg is not None:
        keywords.append(ast.keyword(arg=None, value=ast.Name(id=args.kwarg.arg, ctx=ast.Load())))
    call = ast.Call(
        func=ast.Attribute(
            value=ast.Attribute(value=ast.Name(id="self", ctx=ast.Load()), attr=domain.property_name, ctx=ast.Load()),
            attr=name,
            ctx=ast.Load(),
        ),
        args=positional,
        keywords=keywords,
    )
    result: ast.expr = ast.Await(value=call) if isinstance(source, ast.AsyncFunctionDef) else call
    body: list[ast.stmt] = [
        ast.Expr(
            value=ast.Constant(value=(f"{_summary(source)}\n\nSee :meth:`{domain.module}.{domain.class_name}.{name}`."))
        ),
        ast.Return(value=result),
    ]
    if isinstance(source, ast.AsyncFunctionDef):
        return ast.AsyncFunctionDef(
            name=name,
            args=args,
            body=body,
            decorator_list=[],
            returns=copy.deepcopy(source.returns),
            type_comment=None,
        )
    return ast.FunctionDef(
        name=name,
        args=args,
        body=body,
        decorator_list=[],
        returns=copy.deepcopy(source.returns),
        type_comment=None,
    )


def render() -> str:
    """Render the complete generated module deterministically."""
    imports = "\n".join(sorted(f"from {domain.module} import {domain.class_name}" for domain in OPERATION_CATALOGUE))
    class_lines = [
        "class GeneratedFacade:",
        '    """Generated operation properties and direct facade forwarding."""',
        "",
        "    session: BrainSession",
    ]
    for domain in OPERATION_CATALOGUE:
        class_lines.extend(
            [
                "",
                "    @cached_property",
                f"    def {domain.property_name}(self) -> {domain.class_name}:",
                f'        """The {domain.class_name} operations."""',
                f"        return {domain.class_name}(self.session)",
            ]
        )
        for exported in domain.exports:
            class_lines.extend(["", f"    {exported} = {domain.class_name}.{exported}"])
        if domain.exposure is Exposure.FACADE:
            for operation in domain.operations:
                rendered = ast.unparse(ast.fix_missing_locations(_forwarder(domain, operation)))
                class_lines.extend(["", *[f"    {line}" if line else "" for line in rendered.splitlines()]])
    header = f"""# Generated by ``python -m vitruvio.runtime.generate_facade``. Do not edit by hand.
from __future__ import annotations

from collections.abc import Iterable, Mapping
from functools import cached_property
from pathlib import Path
from typing import Any

{imports}
from vitruvio.runtime.session import BrainSession


"""
    source = header + "\n".join(class_lines) + '\n\n\n__all__ = ["GeneratedFacade"]\n'
    formatter = Path(sys.executable).with_name("ruff")
    completed = subprocess.run(
        [str(formatter), "format", "--stdin-filename", str(TARGET), "-"],
        input=source,
        check=True,
        capture_output=True,
        text=True,
    )
    return completed.stdout


def main(argv: list[str] | None = None) -> int:
    """Write the artifact, or check that the committed copy is current."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    expected = render()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != expected:
            parser.error(f"{TARGET} is stale; run python -m vitruvio.runtime.generate_facade")
        return 0
    TARGET.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":  # pragma: no cover - exercised through subprocess checks
    raise SystemExit(main())
